import EncryptDecryptV4_C
ED = EncryptDecryptV4_C.EncryptDecrypt()

def main():
        ED.decrypt("eTRqdTlyZzJwYjBycjJ2IDNwYjNqdDBjIDJwdDZiIDBjZzR2ZTNqdDVkbzBwdDZyZjFiYzdkIDF2dzRkZTdjbjliZjFrIDlyejh2cjZkazZjbzBkajZpYTZkIDdrNzRrMzZjMDJyIDhwdjJjYjh2YTNkbjlrdjJwdjFqdTVrejNwazdrbjVjIDhpcTdwaDl2IDdjbjhpYjJicTFjbjR2IDZicjB2aDNjbDJ2bzViczZwejZiZjdwIDdkaTJidzhrIDJpajVkYTNicjRrYzhibTd2ZDJyIDN2YTRqbzBpYTR2IDNpcTBrYzdrejFibDZ2IDZkdzdiZTJrdjBqajdqbzN2IDZrbzliZjlrbTFkazljbzNpZDhwYTdiIDRiZjZyeDJkbDhjeTNjbDZjIDBiZDhpZjhpazZpYjR2LDJjIDZjQzlqIDF2aDlybjZwaTRyZDVpIDFjbjdrYzJ2YTFyczB2IDlwbThjYjJpZjVrbjNjIDhkZTRrbjhrIDJibTJjejJwIDRkbzBjbzViZDdiZDRkZTBiYTBkZThpYjdpazBqdTRjIDdyazN2ZThjaDNiZTVpcTRpZQ==")

main()